export const LOGIN_URL = '/login'
export const LOGOUT_URL = '/logout'
export const PROFILE_EDIT_URL = '/profile'
export const REGISTRATION_URL = '/register'
export const SIGNALS_RESERVATION_URL = '/signals/reservation'

export const LOGIN_HASH = 'login'
export const SIGN_UP_HASH = 'sign-up'
export const OPEN_LOGIN_MODAL_EVENT = 'show-modal-login'
export const CLOSE_LOGIN_MODAL_EVENT = 'hide-modal-login'
export const OPEN_SIGN_UP_MODAL_EVENT = 'show-modal-sign-up'
export const CLOSE_SIGN_UP_MODAL_EVENT = 'hide-modal-sign-up'
