CacheRefreshSparkline:          # rake cache_refresh:sparkline
  cron: '0 0 19 * * * Etc/UTC'

GenerateCoinSlugs:              # rake generate_coin_slugs
  cron: '0 0 1 * * * Etc/UTC'

RefreshSitemap:                 # rake sitemap:refresh
  cron: '0 0 0 * * * Etc/UTC'

StakedCofiPerformActions:       # rake staked_cofi:perform_actions
  cron: '0 30 * * * * Etc/UTC'

StakedCofiRefreshTransactions:  # rake staked_cofi:refresh_transactions
  cron: '0 0 * * * * Etc/UTC'

UpdateCurrencies:
  cron: '0 0 0 * * * Etc/UTC'

RefreshTrendingNews:
  cron: '20 */5 * * * * Etc/UTC'  # Stagger start time

TweetTrendingNews:
  cron: '30 0 * * * * Etc/UTC'  # Slightly after RefreshTrendingNews

CheckCmcOhclv:                  # Replaces rake etldb
  cron: '0 50 * * * * Etc/UTC'
  include_metadata: true

RefreshGitRepos:
  cron: '0 15 0 * * * Etc/UTC'

RefreshIndicators:
  cron: '0 20 0 * * * Etc/UTC'

# Paid API routes

UpdateCmcPrices:
  cron: '0 * * * * * Etc/UTC'
  include_metadata: true

UpdateCmcMarketPairs:
  cron: '30 * * * * * Etc/UTC'
  include_metadata: true

UpdateCmcMetrics:
  cron: '50 */5 * * * * Etc/UTC'

UpdateCmcExchanges:
  cron: '0 0 3 * * * Etc/UTC'