CacheRefreshSparkline:          # rake cache_refresh:sparkline
  cron: '0 0 19 * * * Etc/UTC'

GenerateCoinSlugs:              # rake generate_coin_slugs
  cron: '0 0 1 * * * Etc/UTC'

DailyTokenExchangeTransactionsTradingSignalWorker:
  cron: '0 0 1 * * * Etc/UTC'

RefreshSitemap:                 # rake sitemap:refresh
  cron: '0 0 0 * * * Etc/UTC'

StakedCofiPerformActions:       # rake staked_cofi:perform_actions
  cron: '0 30 * * * * Etc/UTC'

StakedCofiRefreshTransactions:  # rake staked_cofi:refresh_transactions
  cron: '0 0 * * * * Etc/UTC'

UpdateCurrencies:
  cron: '0 0 0 * * * Etc/UTC'

RefreshTokenMetricViews:
  cron: '0 0 4 * * * Etc/UTC'   # Scheduled after metrics data is inserted

RefreshTrendingNews:
  cron: '20 */5 * * * * Etc/UTC'  # Stagger start time

TweetTrendingNews:
  cron: '30 0 * * * * Etc/UTC'  # Slightly after RefreshTrendingNews

CheckDailyEtlDb:                # rake etldb:check_daily
  cron: '0 0 2 * * * Etc/UTC'

# Paid API routes

UpdateCmcPrices:
  cron: '0 * * * * * Etc/UTC'
  include_metadata: true

UpdateCmcMarketPairs:
  cron: '30 * * * * * Etc/UTC'
  include_metadata: true

UpdateCmcMetrics:
  cron: '50 */5 * * * * Etc/UTC'

UpdateCmcExchanges:
  cron: '0 0 3 * * * Etc/UTC'