FeedSource.create(name: 'AMBCrypto', feed_url: 'https://ambcrypto.com/feed/', site_url: 'https://ambcrypto.com/')
FeedSource.create(name: 'ALTCOIN.media', feed_url: 'http://altcoin.media/feed/', site_url: 'http://altcoin.media/')
FeedSource.create(name: 'Altcoin Today', feed_url: 'https://altcointoday.com/feed/', site_url: 'https://altcointoday.com/')
FeedSource.create(name: 'BTC Manager', feed_url: 'https://btcmanager.com/feed/', site_url: 'https://btcmanager.com/')
FeedSource.create(name: 'Bitcoin Magazine', feed_url: 'https://bitcoinmagazine.com/feed/', site_url: 'https://bitcoinmagazine.com/')
FeedSource.create(name: 'Bitcoin News', feed_url: 'https://news.bitcoin.com/feed/', site_url: 'https://www.bitcoin.com/')
FeedSource.create(name: 'Bitcoinist', feed_url: 'http://bitcoinist.com/feed/', site_url: 'http://bitcoinist.com/')
FeedSource.create(name: 'Bitfalls', feed_url: 'https://bitfalls.com/feed/', site_url: 'https://bitfalls.com/')
#FeedSource.create(name: 'CoinIdol', feed_url: 'https://coinidol.com/rssshort/', site_url: 'https://coinidol.com/') # Removed due to lack of summary and author fields
FeedSource.create(name: 'Coin Insider', feed_url: 'https://www.coininsider.com/feed/', site_url: 'https://www.coininsider.com/')
FeedSource.create(name: 'CoinSpectator Blog', feed_url: 'https://blog.coinspectator.com/feed/', site_url: 'https://blog.coinspectator.com/')
FeedSource.create(name: 'CoinCap', feed_url: 'http://news.coincap.io/feed/', site_url: 'http://news.coincap.io/')
FeedSource.create(name: 'CoinDesk', feed_url: 'https://www.coindesk.com/feed/', site_url: 'https://www.coindesk.com/')
FeedSource.create(name: 'Coingape', feed_url: 'https://coingape.com/feed/', site_url: 'https://coingape.com/')
FeedSource.create(name: 'CoinJournal', feed_url: 'https://coinjournal.net/feed/', site_url: 'https://coinjournal.net/')
FeedSource.create(name: 'Cointelegraph', feed_url: 'https://cointelegraph.com/feed', site_url: 'https://cointelegraph.com/')
FeedSource.create(name: 'Coindoo', feed_url: 'https://coindoo.com/feed/', site_url: 'https://coindoo.com/')
FeedSource.create(name: 'CoinSpeaker', feed_url: 'https://www.coinspeaker.com/feed', site_url: 'https://www.coinspeaker.com/')
FeedSource.create(name: 'Crypto Answers', feed_url: 'https://cryptoanswers.net/feed/', site_url: 'https://cryptoanswers.net/')
FeedSource.create(name: 'Crypto Insider', feed_url: 'https://cryptoinsider.com/content/feed/', site_url: 'https://cryptoinsider.com/')
FeedSource.create(name: 'Crypto Briefing', feed_url: 'https://cryptobriefing.com/feed/', site_url: 'https://cryptobriefing.com/')
FeedSource.create(name: 'Crypto Daily', feed_url: 'https://cryptodaily.co.uk/feed/', site_url: 'https://cryptodaily.co.uk/')
FeedSource.create(name: 'CryptoNinjas', feed_url: 'https://www.cryptoninjas.net/feed/', site_url: 'https://www.cryptoninjas.net/')
FeedSource.create(name: 'CryptoPost', feed_url: 'http://cryptopost.com/feed/', site_url: 'http://cryptopost.com/')
FeedSource.create(name: 'Cryptovest', feed_url: 'https://cryptovest.com/feed/', site_url: 'https://cryptovest.com/')
FeedSource.create(name: 'ETHNews', feed_url: 'https://www.ethnews.com/rss.xml', site_url: 'https://www.ethnews.com/')
FeedSource.create(name: 'Ethereum World News', feed_url: 'https://ethereumworldnews.com/feed/', site_url: 'https://ethereumworldnews.com/')
FeedSource.create(name: 'ForkLog', feed_url: 'http://forklog.net/feed/', site_url: 'http://forklog.net/')
FeedSource.create(name: 'Howtotoken', feed_url: 'https://howtotoken.com/feed/', site_url: 'https://howtotoken.com/')
FeedSource.create(name: 'Invest In Blockchain', feed_url: 'https://www.investinblockchain.com/feed/', site_url: 'https://www.investinblockchain.com/')
FeedSource.create(name: 'Live Bitcoin News', feed_url: 'http://www.livebitcoinnews.com/feed/', site_url: 'http://www.livebitcoinnews.com/')
FeedSource.create(name: 'NewsBTC', feed_url: 'https://www.newsbtc.com/feed/', site_url: 'https://www.newsbtc.com/')
FeedSource.create(name: 'Profit Confidential', feed_url: 'https://www.profitconfidential.com/feed/', site_url: 'https://www.profitconfidential.com/')
#FeedSource.create(name: 'Quartz', feed_url: 'https://qz.com/feed/', site_url: 'https://qz.com/')
FeedSource.create(name: 'The Bitcoin News', feed_url: 'https://thebitcoinnews.com/feed/', site_url: 'https://thebitcoinnews.com/')
FeedSource.create(name: 'The Daily Hodl', feed_url: 'https://dailyhodl.com/feed/', site_url: 'https://dailyhodl.com/')
FeedSource.create(name: 'Trustnodes', feed_url: 'https://www.trustnodes.com/feed', site_url: 'https://www.trustnodes.com/')
FeedSource.create(name: 'UseTheBitcoin', feed_url: 'https://usethebitcoin.com/feed/', site_url: 'https://usethebitcoin.com/')
